apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-sample-repo-epbt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-sample-repo-epbt
    app.kubernetes.io/part-of: test-app-829
  name: fbc-sample-repo-epbt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: fbc
      app.kubernetes.io/instance: fbc-sample-repo-epbt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fbc
        app.kubernetes.io/instance: fbc-sample-repo-epbt
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-829/fbc-sample-repo-epbt@sha256:a68f55447f7a25be038f16285704c34de1d5d98c7eb0d71346a8608ec9a69295
        name: fbc
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
