apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-2eiy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-parent-image-with-digest-only-2eiy
    app.kubernetes.io/part-of: test-app-829
  name: e2e-tests-parent-image-with-digest-only-2eiy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-2eiy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-2eiy
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-829/e2e-tests-parent-image-with-digest-only-2eiy@sha256:e3fecc1b395f0f7ff9bb0b3dd9788425c136f26f5c7a3678ca503dbfe5ababbd
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
