apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: retrodep-snf1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: retrodep-snf1
    app.kubernetes.io/part-of: test-app-829
  name: retrodep-snf1
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-retrodep
      app.kubernetes.io/instance: retrodep-snf1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-retrodep
        app.kubernetes.io/instance: retrodep-snf1
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-829/retrodep-snf1@sha256:d3706e0f3a756251887cb05c65bad7d51a125092026f6359a50e75fea8db3dec
        name: my-retrodep
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
