apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pip-e2e-test-vrzv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pip-e2e-test-vrzv
    app.kubernetes.io/part-of: test-app-829
  name: pip-e2e-test-vrzv
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pip-e2e-test
      app.kubernetes.io/instance: pip-e2e-test-vrzv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pip-e2e-test
        app.kubernetes.io/instance: pip-e2e-test-vrzv
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-829/pip-e2e-test-vrzv@sha256:8861ed4a0cc71bf14f87fd1671893d14957d87588aa71b7b32cde1e4a4e31348
        name: pip-e2e-test
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
