apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maven-hello-world-hiwq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maven-hello-world-hiwq
    app.kubernetes.io/part-of: test-app-829
  name: maven-hello-world-hiwq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: maven-hello-world-hiwq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: maven-hello-world-hiwq
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-829/maven-hello-world-hiwq@sha256:4a7731e32b96495e3b46dce63575fbb67c878b46f3a2b0f56ad70e0b07312720
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
